<a href="https://colab.research.google.com/github/spursbyte/python_research_ml/blob/main/day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#functions
def sum_prod(in1,in2):
  sum= in1+in2
  prod=in1*in2
  print('sum=' + str(sum))
  print('prod=' + str(prod))
  return sum,prod


In [3]:
sum_prod(2,7) # output returned as a tuple

sum=9
prod=14


(9, 14)

In [4]:
result= sum_prod(5,-8)

sum=-3
prod=-40


In [6]:
print(result[1],result[0])

-40 -3


In [11]:
# lambda functions
res = lambda x: x ** 2 - 4
print(res(2))

0


In [19]:
#exercise factorial function
def factorial(n):
  return np.prod(np.arange(1,n+1))


In [12]:
import numpy as np


In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.prod(np.arange(1,4+1))

24

siddharth->0.5


In [21]:
fact1= factorial(6)
print(fact1)

720


In [22]:
import math


In [23]:
math.factorial(6)

720

In [24]:
math.factorial(0)

1

In [25]:
factorial(0)

1

In [26]:
#Scope of variables
#inside a fun scope is local(only accesssible within the fun)->local var
#both accessible inside and outside fun-> global var
def fun():
  print(z)

In [27]:
z=3
fun()

3


In [29]:
import numpy as np


In [34]:
#exercise write a fun that flips a coin n times and return the avg
def flip(n):
 return np.mean(np.random.randn(n)>0)



In [31]:
np.random.randn(5)

array([ 1.66349811,  0.07584933,  0.401433  , -0.33376547, -0.51365007])

In [32]:
np.random.randn(5)>0


array([ True, False, False, False,  True])

In [33]:
np.mean(np.random.randn(5)>0)

0.8

In [36]:
flip(9)

0.5555555555555556

In [43]:
#flow control statements

#if else statemnts
r=np.random.randn()
if r>0:
  print(str(r)+ ' is positive')
else:
  print(str(r)+' is negative')

-1.0357846708488667 is negative
